spring:
  datasource:
    hikari:
      pool-name: frog-pool
      driver-class-name: org.mariadb.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 50
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ## 아래 옵션을 사용하면 engine=InnoDB 옵션을 활성화 하고 볼 수 있다.
        #        dialect: org.hibernate.dialect.MySQL57Dialect
        id.new_generator_mappings: false
        hbm2ddl:
          auto: validate
    show-sql: true
  profiles:
    active: local

---
spring.profiles: local
spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:frog-todo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        format_sql: false
        hbm2ddl:
          auto: update
